[package]
name = "kind-cli"
version = "0.3.0"
edition = "2021"
description = "A pure functional functional language that uses the HVM."
repository = "https://github.com/Kindelia/Kind2"
license = "MIT"
keywords = ["functional", "language", "type-theory", "proof-assistant"]

[[bin]]
name = "kind"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind-driver  = { path = "../kind-driver" }
kind-report  = { path = "../kind-report" }
kind-checker = { path = "../kind-checker" }
kind-query = { path = "../kind-query" }

clap = { version = "4.0.10", features = ["derive"] }
anyhow = "1.0.66"
exitcode = "1.1.2"