[package]
edition = "2021"
license = "MIT"
name = "kind-syntax"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.3"
thin-vec = "0.2.12"
